#import "RNMeasuredCellView.h"

// Generated by codegen from RNCollectionViewSpec (package.json codegenConfig).
// Available after `pod install` runs the RN codegen step.
#import <react/renderer/components/RNCollectionViewSpec/ComponentDescriptors.h>
#import <react/renderer/components/RNCollectionViewSpec/EventEmitters.h>
#import <react/renderer/components/RNCollectionViewSpec/Props.h>
#import <react/renderer/components/RNCollectionViewSpec/RCTComponentViewHelpers.h>

#import <React/RCTFabricComponentsPlugins.h>

using namespace facebook::react;

@interface RNMeasuredCellView () <RCTRNMeasuredCellViewProtocol>
@end

@implementation RNMeasuredCellView {
  // Last size reported via onMeasured — used to suppress duplicate events
  // when layoutSubviews is called but the size hasn't actually changed.
  CGSize _lastFiredSize;
}

// ── Fabric registration ────────────────────────────────────────────────────────

+ (ComponentDescriptorProvider)componentDescriptorProvider
{
  return concreteComponentDescriptorProvider<RNMeasuredCellComponentDescriptor>();
}

// ── Initialisation ─────────────────────────────────────────────────────────────

- (instancetype)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    static const auto defaultProps = std::make_shared<const RNMeasuredCellProps>();
    _props = defaultProps;
    _lastFiredSize = CGSizeZero;
  }
  return self;
}

// ── Layout ─────────────────────────────────────────────────────────────────────

- (void)layoutSubviews
{
  [super layoutSubviews];

  CGSize size = self.bounds.size;

  // Skip if size hasn't changed or is degenerate (view not yet laid out).
  if (CGSizeEqualToSize(size, _lastFiredSize)) return;
  if (size.height <= 0) return;

  _lastFiredSize = size;

  if (_eventEmitter) {
    auto emitter = std::static_pointer_cast<RNMeasuredCellEventEmitter const>(_eventEmitter);
    RNMeasuredCellEventEmitter::OnMeasured event;
    event.height = static_cast<Float>(size.height);
    event.width  = static_cast<Float>(size.width);
    emitter->onMeasured(event);
  }
}

@end

// Required export so the Fabric component registry can find this view class.
Class<RCTComponentViewProtocol> RNMeasuredCellCls(void)
{
  return RNMeasuredCellView.class;
}
