#import "RNMeasuredCellView.h"

// Generated by codegen from RNCollectionViewSpec (package.json codegenConfig).
// Available after `pod install` runs the RN codegen step.
#import <react/renderer/components/RNCollectionViewSpec/ComponentDescriptors.h>
#import <react/renderer/components/RNCollectionViewSpec/EventEmitters.h>
#import <react/renderer/components/RNCollectionViewSpec/Props.h>
#import <react/renderer/components/RNCollectionViewSpec/RCTComponentViewHelpers.h>

#import <React/RCTFabricComponentsPlugins.h>

using namespace facebook::react;

#ifndef RNCV_ENABLE_NATIVE_LOGS
#define RNCV_ENABLE_NATIVE_LOGS 0
#endif

#if DEBUG && RNCV_ENABLE_NATIVE_LOGS
  #define RNCV_IOS_MEASURED_LOG(...) NSLog(__VA_ARGS__)
#else
  #define RNCV_IOS_MEASURED_LOG(...) ((void)0)
#endif

@interface RNMeasuredCellView () <RCTRNMeasuredCellViewProtocol>
@end

@implementation RNMeasuredCellView {
  // Last size reported via onMeasured — used to suppress duplicate events
  // when layoutSubviews is called but the size hasn't actually changed.
  CGSize _lastFiredSize;
}

// ── Fabric registration ────────────────────────────────────────────────────────

+ (ComponentDescriptorProvider)componentDescriptorProvider
{
  return concreteComponentDescriptorProvider<RNMeasuredCellComponentDescriptor>();
}

// ── Initialisation ─────────────────────────────────────────────────────────────

- (instancetype)initWithFrame:(CGRect)frame
{
  if (self = [super initWithFrame:frame]) {
    static const auto defaultProps = std::make_shared<const RNMeasuredCellProps>();
    _props = defaultProps;
    _lastFiredSize = CGSizeZero;
  }
  return self;
}

// ── Fabric layout metrics ──────────────────────────────────────────────────────
// Prevent Fabric's default updateLayoutMetrics: from overwriting the cache-based
// position set by the container's applyPositionsFromState.  Yoga computes a
// sequential flex-column layout (wrong for Collection View items).  We only
// forward SIZE changes so Yoga-measured dimensions are applied; POSITION is
// preserved so applyPositionsFromState remains the single source of truth.
//
// IMPORTANT: We use self.frame.origin (the ACTUAL current native position),
// NOT oldLayoutMetrics.frame.origin (which contains the PREVIOUS Yoga position).
// After applyPositionsFromState sets the correct cache-based position,
// self.frame.origin holds that correct value.  oldLayoutMetrics would just
// hold the prior Yoga-computed origin and re-applying it defeats the purpose.

- (void)updateLayoutMetrics:(const facebook::react::LayoutMetrics &)layoutMetrics
           oldLayoutMetrics:(const facebook::react::LayoutMetrics &)oldLayoutMetrics
{
  auto adjusted = layoutMetrics;
  // Preserve the current native position — it was set by applyPositionsFromState
  // and is the source of truth for POSITION.
  adjusted.frame.origin.x = self.frame.origin.x;
  adjusted.frame.origin.y = self.frame.origin.y;
  // Also preserve the current native size if Yoga reports 0.
  // Yoga may measure a cell as 0-height before content is committed.
  // applyPositionsFromState sets the correct size from the LayoutCache.
  // Letting Yoga overwrite with 0 makes children invisible.
  if (adjusted.frame.size.height <= 0 && self.frame.size.height > 0) {
    adjusted.frame.size.height = self.frame.size.height;
  }
  if (adjusted.frame.size.width <= 0 && self.frame.size.width > 0) {
    adjusted.frame.size.width = self.frame.size.width;
  }
  [super updateLayoutMetrics:adjusted oldLayoutMetrics:oldLayoutMetrics];
}

// ── Layout ─────────────────────────────────────────────────────────────────────

- (void)layoutSubviews
{
  [super layoutSubviews];

  CGSize size = self.bounds.size;

  // Skip if size hasn't changed or is degenerate (view not yet laid out).
  if (CGSizeEqualToSize(size, _lastFiredSize)) return;
  if (size.height <= 0) return;

  _lastFiredSize = size;
  const auto props = std::static_pointer_cast<const RNMeasuredCellProps>(_props);
  const int index = props ? (int)props->index : -1;
  const char *type = props ? props->type.c_str() : "";
  const char *kind = props ? props->kind.c_str() : "";
  const char *cacheKey = props ? props->cacheKey.c_str() : "";
  RNCV_IOS_MEASURED_LOG(@"[RNCV-IOS-MEASURED] tag:%ld index:%d type:%s kind:%s cacheKey:%s frame=(%.1f,%.1f,%.1f,%.1f) measured=(%.1f,%.1f)",
                        (long)self.tag,
                        index,
                        type,
                        kind,
                        cacheKey,
                        self.frame.origin.x, self.frame.origin.y, self.frame.size.width, self.frame.size.height,
                        size.width, size.height);

  if (_eventEmitter) {
    auto emitter = std::static_pointer_cast<RNMeasuredCellEventEmitter const>(_eventEmitter);
    RNMeasuredCellEventEmitter::OnMeasured event;
    event.height = static_cast<Float>(size.height);
    event.width  = static_cast<Float>(size.width);
    emitter->onMeasured(event);
  }
}

@end

// Required export so the Fabric component registry can find this view class.
Class<RCTComponentViewProtocol> RNMeasuredCellCls(void)
{
  return RNMeasuredCellView.class;
}
